name: AI Agent CRON Job

on:
  schedule:
    - cron: "30 21,0,4,6,8,10,12,14,16,18 * * *"
  workflow_dispatch:  

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"

      - name: Install Dependencies
        run: pip install -r python-requirements.txt

      - name: Run process_scheduler.py
        env:
          GOOGLE_GENAI_API_KEY: ${{ secrets.GOOGLE_GENAI_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          WEBSCRAPER_API_URL: ${{ secrets.WEBSCRAPER_API_URL }}
        run: python process_scheduler.py
